// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[admin_token]/allow_list/[name]/delete.tsx";
import * as $1 from "./routes/[admin_token]/allow_list/index.tsx";
import * as $2 from "./routes/[admin_token]/background.tsx";
import * as $3 from "./routes/[admin_token]/cards/[card_id]/delete.tsx";
import * as $4 from "./routes/[admin_token]/cards/index.tsx";
import * as $5 from "./routes/[admin_token]/color.tsx";
import * as $6 from "./routes/[admin_token]/index.tsx";
import * as $7 from "./routes/[admin_token]/logo.tsx";
import * as $8 from "./routes/[admin_token]/title.tsx";
import * as $9 from "./routes/_404.tsx";
import * as $10 from "./routes/_app.tsx";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/theme.css.tsx";

const manifest = {
  routes: {
    "./routes/[admin_token]/allow_list/[name]/delete.tsx": $0,
    "./routes/[admin_token]/allow_list/index.tsx": $1,
    "./routes/[admin_token]/background.tsx": $2,
    "./routes/[admin_token]/cards/[card_id]/delete.tsx": $3,
    "./routes/[admin_token]/cards/index.tsx": $4,
    "./routes/[admin_token]/color.tsx": $5,
    "./routes/[admin_token]/index.tsx": $6,
    "./routes/[admin_token]/logo.tsx": $7,
    "./routes/[admin_token]/title.tsx": $8,
    "./routes/_404.tsx": $9,
    "./routes/_app.tsx": $10,
    "./routes/index.tsx": $11,
    "./routes/theme.css.tsx": $12,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
